"""This module provides functions for agent income_generation.

Functions:
- income_generation: Directs arguments to method-specific internal functions
- _pseudo_income_generator: Determines income based on static TechTable
- _income_generator: Determines income based on available technology and costs
"""
import numpy as np
import torch


def income_generation(model_graph, device, params=None, 
                      method='pseudo_income_generation'):
    """Calculate income generated by agents, multiple methods available.
    
    Args:
        model_graph (DGLGraph): All agent node and edge data
        device (torch.device): Device on which to perform computations
        params (dict): Parameters specified in model configuration and initialization
        method (str): Method used for generating income

    Returns:
        None
    """
    if method == 'pseudo_income_generation':
        _pseudo_income_generator(model_graph)    
    elif method == 'income_generation':
        _income_generator(model_graph,device, params)
    else:
        raise NotImplementedError(f'Income generation method "{method}" unavailable')
    

def _pseudo_income_generator(model_graph):
    """Generate income for agents based on wealth and alpha for static TechTable.
    
    Arg:
        model_graph (DGLGraph): All agent data

    Returns:
        None
    """
    tech_table =  np.array([[0.3,0],[0.35,0.15],[0.45, 0.65]])

    model_graph.ndata['income'] = (torch.max((model_graph.ndata['alpha'][:,None]*
                                model_graph.ndata['wealth'][:,None]**tech_table[:,0] - 
                                tech_table[:,1]), axis=1)[0].to(torch.float32))

def _income_generator(model_graph, device, params):
    """Generate income for agents based on wealth and alpha.
     
    Notes: Maximum income is based on available technology options and costs.
        The quation format follows a capital-only Cobb-Douglas production function.
    
    Args:
        model_graph (DGLGraph): All agent data
        device (torch.device): Device on which to perform computations
        params (dict): Parameters specified in model configuration and initialization

    Returns:
        None
    """
    gamma = params['tech_gamma'].to(device)
    cost = params['tech_cost'].to(device)
    model_graph.ndata['income'],model_graph.ndata['tech_index'] = (
                    torch.max((model_graph.ndata['alpha'][:,None] * 
                    model_graph.ndata['wealth'][:,None]**gamma - cost), axis=1))
    print(f"Income:{model_graph.ndata['income'][0:5]}")