# Changes here will be overwritten by Copier
SelectCitation:
- AddCitationFile_flag
- AddCFFConvert_flag
SelectCodeQualityFeatures:
- AddLocalTests_flag
- SelectGitHubActions_flag
- AddLinting_flag
- AddSonarCloud_flag
- AddEditorConfig_flag
SelectCommunityFeatures:
- AddCodeConduct_flag
- AddContributing_flag
SelectDocumentationFeatures:
- AddLocalDocumentation_flag
- AddOnlineDocumentation_flag
- AddDevDoc_flag
- AddGitHubActionDocumentation_flag
SelectGitHubActions:
- AddGitHubActionBuild_flag
- AddLinkCheck_flag
SelectPublishReleaseFeatures:
- SelectCitation_flag
- AddChangeLog_flag
- AddZenodo_flag
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
code_of_conduct_email: m.grootes@esciencecenter.nl
copyright_holder: Meiert W. Grootes
email: m.grootes@esciencecenter.nl
full_name: Meiert W. Grootes
github_organization: SDCCA
keywords: ABM, Tensor, PyTorch
license: Apachev2
package_name: dgl_abm
package_short_description: ABM modelling framework using networks and tensor algebra
    supported by the DGL library
template_profile: recommended
version: 0.1.0
