name: dgl_abm_mac
channels:
  - defaults
  - dglteam
  - pytorch
dependencies:
  - python>=3.10,<3.11
  # Runtime
  - pip
  - pydantic=2.11.7
  - yaml=0.2.5
  - xarray
  - zarr
  # Development/Testing
  - pytest
  - pytest-cov
  - ruff
  - python-build